### ISSUE TITLE
what is "throughout the simulation" in Figure 5?

### ISSUE THREAD

**Issue by petrelharp** [jgallowa07/SticklebackPaper#4]
I see that the number of FAA is recorded for every generation, but are all these generations used in creating the plot?

**Comment by petrelharp** [comment]
This is now Figure 6.

**Comment by jaredgalloway** [comment]
No, just all generations s.t (sim.gen % 50 == 0), so every 50 gens the number is recorded and the distribution is representative of all those numbers.
